Docker issues

diff --git a/.github/workflows/nuxtjs.yml b/.github/workflows/nuxtjs.yml
--- a/.github/workflows/nuxtjs.yml
+++ b/.github/workflows/nuxtjs.yml
@@ -12,17 +12,6 @@ on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
-permissions:
-  contents: read
-  pages: write
-  id-token: write
-
-# Allow one concurrent deployment
-concurrency:
-  group: "pages"
-  cancel-in-progress: true
-
 jobs:
   # Build job
   build:
@@ -31,57 +20,43 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Detect package manager
-        id: detect-package-manager
-        run: |
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine packager manager"
-            exit 1
-          fi
+  #     - name: Detect package manager
+  #       id: detect-package-manager
+  #       run: |
+  #         if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+  #           echo "manager=yarn" >> $GITHUB_OUTPUT
+  #           echo "command=install" >> $GITHUB_OUTPUT
+  #           exit 0
+  #         elif [ -f "${{ github.workspace }}/package.json" ]; then
+  #           echo "manager=npm" >> $GITHUB_OUTPUT
+  #           echo "command=ci" >> $GITHUB_OUTPUT
+  #           exit 0
+  #         else
+  #           echo "Unable to determine packager manager"
+  #           exit 1
+  #         fi
 
-      - name: Setup Node
-        uses: actions/setup-node@v3
-        with:
-          node-version: "16"
-          cache: ${{ steps.detect-package-manager.outputs.manager }}
+  #     - name: Setup Node
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: "16"
+  #         cache: ${{ steps.detect-package-manager.outputs.manager }}
 
-      # - name: Setup Pages
-      #   uses: actions/configure-pages@v3
-      #   with:
-      #     # Automatically inject router.base in your Nuxt configuration file and set
-      #     # target to static (https://nuxtjs.org/docs/configuration-glossary/configuration-target/).
-      #     #
-      #     # You may remove this line if you want to manage the configuration yourself.
-      #     static_site_generator: nuxt
+  #     - name: Restore cache
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: |
+  #           dist
+  #           .nuxt
+  #         key: ${{ runner.os }}-nuxt-build-${{ hashFiles('dist') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-nuxt-build-
 
-      - name: Restore cache
-        uses: actions/cache@v3
-        with:
-          path: |
-            dist
-            .nuxt
-          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('dist') }}
-          restore-keys: |
-            ${{ runner.os }}-nuxt-build-
+  #     - name: Install dependencies
+  #       run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
 
-      - name: Install dependencies
-        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
-
-      - name: Build
-        run: ${{ steps.detect-package-manager.outputs.manager }} run build
-
-      # - name: Upload artifact
-      #   uses: actions/upload-pages-artifact@v1
-      #   with:
-      #     path: ./.output
+  #     - name: Build
+  #       run: ${{ steps.detect-package-manager.outputs.manager }} run build
 
   # Deployment job
   deploy:
@@ -91,10 +66,6 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     steps:
-      # - name: Deploy to GitHub Pages
-      #   id: deployment
-      #   uses: actions/deploy-pages@v1
-
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
